var SimVolante = {
    "DataResult": [
        {
            "NU_MANI": "2016-012341",
            "NU_GUIA_MADR": "045123456781",
            "NU_GUIA": "045123456781",
            "NU_VOLA_MADR": "0015678",
            "NU_VOLA": "00123456",
            "CO_ENTI_LINE": "CV",
            "DE_ENTI_LINE": "CARGOLUX AIRLINES INTERNATIONAL, S.A.",
            "NU_VUEL": "7783",
            "FE_LLEG_VUEL": "12/12/2015",
            "FE_LLEG_ALMA": "15/12/2015",
            "DE_CIUD_ORIG": "LUXEMBOURG -- LUXEMB",
            "DE_CIUD_DEST": "MEXICO CITY -- MEXIC",
            "DE_AGEN_RECE": "CAPITAL LOGISTICS SA DE CV",
            "DE_AGEN_ENBA": "VARIOS",
            "NU_BULT_RECI": "165",
            "KG_RECI": "153.20",
            "TP_INGR": "NORMAL (SOLO PEDIMENTOS)",
            "DE_CARG":" VARIOS AUOPARTES",
            "DE_CONS":"NINGUNO",
            "ST_INVE":"S"
        },
          {
              "NU_MANI": "2016-012341",
              "NU_GUIA_MADR": "045123456781",
              "NU_GUIA": "045123456781",
              "NU_VOLA_MADR": "0015678",
              "NU_VOLA": "00123457",
              "CO_ENTI_LINE": "CV",
              "DE_ENTI_LINE": "CARGOLUX AIRLINES INTERNATIONAL, S.A.",
              "NU_VUEL": "7783",
              "FE_LLEG_VUEL": "12/12/2015",
              "FE_LLEG_ALMA": "15/12/2015",
              "DE_CIUD_ORIG": "LUXEMBOURG -- LUXEMB",
              "DE_CIUD_DEST": "MEXICO CITY -- MEXIC",
              "DE_AGEN_RECE": "CAPITAL LOGISTICS SA DE CV",
              "DE_AGEN_ENBA": "VARIOS",
              "NU_BULT_RECI": "165",
              "KG_RECI": "153.20",
              "TP_INGR": "NORMAL (SOLO PEDIMENTOS)",
              "DE_CARG": " VARIOS AUOPARTES",
              "DE_CONS": "NINGUNO",
              "ST_INVE": "S"
          },
             {
                 "NU_MANI": "2016-012341",
                 "NU_GUIA_MADR": "045123456781",
                 "NU_GUIA": "045123456781",
                 "NU_VOLA_MADR": "0015678",
                 "NU_VOLA": "00123458",
                 "CO_ENTI_LINE": "CV",
                 "DE_ENTI_LINE": "CARGOLUX AIRLINES INTERNATIONAL, S.A.",
                 "NU_VUEL": "7783",
                 "FE_LLEG_VUEL": "12/12/2015",
                 "FE_LLEG_ALMA": "15/12/2015",
                 "DE_CIUD_ORIG": "LUXEMBOURG -- LUXEMB",
                 "DE_CIUD_DEST": "MEXICO CITY -- MEXIC",
                 "DE_AGEN_RECE": "CAPITAL LOGISTICS SA DE CV",
                 "DE_AGEN_ENBA": "VARIOS",
                 "NU_BULT_RECI": "165",
                 "KG_RECI": "153.20",
                 "TP_INGR": "NORMAL (SOLO PEDIMENTOS)",
                 "DE_CARG": " VARIOS AUOPARTES",
                 "DE_CONS": "NINGUNO",
                 "ST_INVE": "S"
             },
    ]
};